gatsby-tv/westegg

- src/entities/User.ts
- src/routes/user.ts
Leave #24 open, as this is just a small part of it.
> Cleanup already finished or obsolete TODOs

- .travis.yml
> Build only on master

- src/environment.ts
> Validate environment variables

- src/environment.ts
> Allowed dashes in mongo host name

- package-lock.json
- package.json
- src/middleware/video.ts
- src/routes/video.ts
> Add video puts

- package-lock.json
- package.json
- src/middleware/user.ts
- src/routes/user.ts
> Add user put nesbitt

- package-lock.json
- package.json
- src/entities/User.ts
- src/routes/user.ts
> Make email unique nesbitt

- src/environment.ts
> 52 sendgrid key validation nesbitt

- default.env
- docker-compose.yml
- mongo/init.sh
- src/db.ts
- src/environment.ts
> Made MongoDB user an env var

- src/middleware/index.ts
- src/routes/auth.ts
- src/routes/channel.ts
- src/routes/user.ts
- src/routes/video.ts
> 62 put body validaiton nesbitt

- src/environment.ts
> Validate mongo root password

- .env.development
- src/entities/Video.ts
- src/routes/listing.ts
> westegg#44 Fix videos to use objectid channel foriegn key

- packages/types/lib/requests.ts
- packages/types/lib/responses.ts
- packages/types/lib/types.ts
- packages/types/scripts/build.js
- src/routes/listing.ts
Also fixed a bit of imports using relative paths in types repo instead of aliases.
> feature: Update listing routes to use cursors (replace paging) (#87)

- src/db.ts
> bugfix: Fix deprecated mongoose connection setup (#82)

- .travis.yml
- packages/types/Makefile
> feature: Update types to use new travis ci build (#97)

- src/routes/listing.ts
> feature: Add duplicate videos to listing routes to fill empty responses

- packages/types/lib/requests.ts
- src/entities/Base.ts
- src/entities/Channel.ts
- src/entities/User.ts
- src/entities/Video.ts
- src/middleware/auth.ts
- src/middleware/channel.ts
- src/middleware/multipart.ts
- src/middleware/video.ts
- src/routes/channel/index.ts
- src/routes/user/index.ts
- src/routes/video/index.ts
> cleanup: Remove all todos, create issues instead (#24)

- package.json
- src/index.ts
- yarn.lock
> feature: Log http request metadata with winston express middleware (#134)

- tsconfig.json
> bugfix: Added path alias for types repo (#141)

- src/routes/listing/index.ts
> feature: Added proper response for featured channels route (#145)

- src/entities/Channel.ts
- src/entities/IPFSContent.ts
> feature: Add channel poster and banner schema

- packages/types/lib/requests.ts
- packages/types/lib/responses.ts
- src/routes/user/index.ts
> feature: Added route for getting user channels. (#155)

- packages/types/lib/requests.ts
- packages/types/lib/responses.ts
- src/index.ts
- src/routes/video/tags.ts
- tsconfig.json
Note does not fully close #159, still needs more work.
> feature: Add/remove/get video tags (#159)

- packages/types/lib/requests.ts
- packages/types/lib/responses.ts
- src/routes/listing/index.ts
> feature: Filter videos by tag(s) (#159)
